### ISSUE TITLE
AMI is not avaialble and Linux fix

### ISSUE THREAD

**Issue by acaN** [joshpmcghee/parsec-terraform#2]
Hello!

Thank you for a great work!

There is some issues as of Jan, 2017, though:

First one (and critical) is that AMI image is not found with default settings. Workaroung is to use parsec default one, but pre-installed steam is a nice-to-have feature. Also, auth code is now requires an email address too, so without a fix, instance do not appear in parsec webpage.

Second, only linux-related is that "date" command works a little differently on Linux (or mingw), with -d key absent (different syntax). Correct one would be "date -d "-1 day"" to get current date.
Also, any locale other than EN would give us a python utf decode error, so i also added LANG=en_US in front of date command.
Just maybe it would be helpful for someone, maybe include it to README file.

So, i would be glad if steam-preinstalled AMI will become available again.

Thanks!

**Comment by yanneves** [comment]
I've configured to use latest AMI instance in #5
